#!/bin/sh
curl -fsS "https://raw.githubusercontent.com/ernestoittig/mytools/master/rmd/rmd"  > "$HOME/.local/bin/rmd"
curl -fsS "https://raw.githubusercontent.com/ernestoittig/mytools/master/rmd/rmd.1" > "/usr/local/share/man/man1/rmd.1"