.\" Manpage for rmd.
.TH RMD 1 "2019-05-07" "GNU" "General Commands Manual"
.SH NAME
rmd \- compile R markdown 
.SH SYNOPSIS
rmd 
.I filename
.SH DESCRIPTION
rmd is a script for compiling R markdown from the command-line.  For it to work, R and the rmarkdown package must already be installed
.SH OPTIONS
The rmd does not take any options. However, you must supply a filename
.SH SEE ALSO
R(1)
.SH AUTHOR
Ernesto Ittig
